@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

InternWatcher *-right-> "1" UniqueApplicantList
InternWatcher *-right-> "1" UniqueSkillList
UniqueSkillList -[hidden]down- UniqueApplicantList
UniqueSkillList -[hidden]down- UniqueApplicantList

UniqueSkillList *-right-> "*" Skill
UniqueApplicantList -right-> Applicant

Applicant -up-> "*" Skill

Applicant *--> Name
Applicant *--> Phone
Applicant *---> Email
Applicant *---> Course
Applicant *---> ApplicationStatus
Applicant *---> Job
Applicant *---> GraduationYearMonth
Applicant *--> Grade
Applicant *--> Institution

@enduml
