@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternWatcherParser" as InternWatcherParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> InternWatcherParser : parseCommand("delete 1")
activate InternWatcherParser

create DeleteCommandParser
InternWatcherParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> InternWatcherParser
deactivate DeleteCommandParser

InternWatcherParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> InternWatcherParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> InternWatcherParser
destroy DeleteCommandParser

InternWatcherParser --> LogicManager : d
deactivate InternWatcherParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deleteApplicant(1)
activate Model

Model --> DeleteCommand
DeleteCommand -> Model : commitInternWatcher(commitMessage)
activate Model

Model -> Model : commitState(commitMessage)
Model --> Model

deactivate Model
Model --> DeleteCommand

deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
