@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyInternWatcher <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class InternWatcher
Class ReadOnlyInternWatcher
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueApplicantList
Class Applicant
Class Phone
Class Name
Class Grade
Class Institution
Class Job
Class ApplicationStatus
Class Course
Class Email
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

InternWatcher .up.|> ReadOnlyInternWatcher

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyInternWatcher
ModelManager -left-> "1" InternWatcher
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

InternWatcher *--> "1" UniqueApplicantList
UniqueApplicantList --> "~* all" Applicant
Applicant *--> Name
Applicant *--> Grade
Applicant *--> Institution
Applicant *--> Job
Applicant *--> ApplicationStatus
Applicant *--> Course
Applicant *--> Email

ModelManager -->"~* filtered" Applicant
@enduml
