@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyInternWatcher <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class InternWatcher
Class ReadOnlyInternWatcher
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class UniquePersonList
Class Applicant
Class Email
Class Name
Class Phone
Class Skill
Class Job
Class Grade
Class GraduationYearMonth
Class ApplicationStatus
Class Course
Class Institution
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

InternWatcher .up.|> ReadOnlyInternWatcher

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyInternWatcher
ModelManager -left-> "1" InternWatcher
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

InternWatcher *--> "1" UniquePersonList
UniquePersonList --> "~* all" Applicant
Applicant *--> Name
Applicant *--> Phone
Applicant *--> Email
Applicant *--> Course
Applicant *--> "*" Skill
Applicant *--> ApplicationStatus
Applicant *--> Job
Applicant *--> GraduationYearMonth
Applicant *--> Grade
Applicant *--> Institution

Name -[hidden]right-> Phone
Phone -[hidden]right-> Course
Course -[hidden]right-> Email
Email -[hidden]right-> Grade
Grade -[hidden]right-> GraduationYearMonth
GraduationYearMonth -[hidden]right-> Institution
Institution -[hidden]right-> Job
Job -[hidden]right-> Skill

ModelManager -->"~* filtered" Applicant
@enduml
