@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "InternWatcher Storage" #F4F6F6{
Interface InternWatcherStorage <<Interface>>
Class JsonInternWatcherStorage
Class JsonSerializableInternWatcher
Class JsonAdaptedApplicant
Class JsonAdaptedSkill
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" InternWatcherStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> InternWatcherStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonInternWatcherStorage .up.|> InternWatcherStorage
JsonInternWatcherStorage ..> JsonSerializableInternWatcher
JsonSerializableInternWatcher --> "*" JsonAdaptedApplicant
JsonAdaptedApplicant --> "*" JsonAdaptedSkill
@enduml
