@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternWatcherParser" as InternWatcherParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedInternWatcher" as VersionedInternWatcher MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> InternWatcherParser : parseCommand(undo)
activate InternWatcherParser

create UndoCommand
InternWatcherParser -> UndoCommand
activate UndoCommand

UndoCommand --> InternWatcherParser
deactivate UndoCommand

InternWatcherParser --> LogicManager : u
deactivate InternWatcherParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoInternWatcher()
activate Model

Model -> VersionedInternWatcher : undo()
activate VersionedInternWatcher

VersionedInternWatcher -> VersionedInternWatcher :resetData(ReadOnlyInternWatcher)
VersionedInternWatcher --> Model :
deactivate VersionedInternWatcher

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
